name: pipeline

on: [ push, workflow_dispatch ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: setup bun
        uses: oven-sh/setup-bun@v1

      - name: create package version
        shell: bash
        if: github.ref != 'refs/heads/master'
        run: |
          current_version=$(cat package.json | jq -r '.version')
          current_branch_raw=$(echo $GITHUB_REF | sed 's/refs\/heads\///' | sed 's/refs\/tags\///')
          current_branch=$(echo $current_branch_raw | sed 's/\//-/g')
          current_commit=$(echo $GITHUB_SHA | cut -c1-8)

          project_version="${current_version}-${current_branch}.${current_commit}"
          echo $(jq ".version = \"$project_version\"" package.json) > package.json

      - name: echo package version
        shell: bash
        run: echo $(cat package.json | jq -r '.version')

      - name: setup .npmrc
        shell: bash
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          echo "@vichava:registry=https://npm.pkg.github.com/" >> ~/.npmrc

      - name: install dependencies
        shell: bash
        run: bun i

      - name: publish
        shell: bash
        run: ./publish.sh
